### ISSUE TITLE
coloredlogs 14.0 for py10 (or noarch!)

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/coloredlogs-feedstock#33]
Thanks for maintaining this.

It seems like this getting its py310 migration unblocked `dagster-feedstock` getting migrated... 

https://github.com/conda-forge/dagster-feedstock/pull/169

...but it has a pin on an older version of `coloredlogs`...

https://github.com/conda-forge/dagster-feedstock/blob/1bc8a6dbdeba02f3e35733a2a732427e8f693181/recipe/meta.yaml#L189

Would it be possible to get a historical build of `14.0` which works with py310?

It looks like there's nothing too freaky going on, so maybe noarch forked off #21 would be the lightest touch.

Alternately, I could do a `noarch` PR to master, which might make the backport slightly simpler.

I'll work the upstream angle, as well.

**Comment by ocefpaf** [comment]
Building at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=422229&view=results

**Comment by bollwyvl** [comment]
Thanks!
